title: "Martin Seongsoon Park"
description: "This is my github page blog"
about: "Hi, I am a Full Stack Developer looking for awesome opportunities. I love making, building, and developing fun and interactive applications!"
location: "New York, New York"
email: sp3005@nyu.edu
baseurl: ""

url: "http://outpark.github.io/" # replace by your site's url
twitter_username: outpark
github_username:  outpark
author: "Martin Park"

# google analytics tracking code, please change the value
g_analytics: ""

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
about_btn: "About"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
